server:
  port: 8082

spring:
  application:
    name: notification-dispatcher

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-dispatcher-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.contract.NotificationEvent


  data:
    redis:
      host: redis
      port: 6379

dispatcher:
  retry:
    max-attempts: 3
